# Generated by Django 4.2.2 on 2023-07-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Wishlist', '0002_alter_wishlist_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
